import { ethers } from "hardhat";
import fs from "fs";
import path from "path";

async function main() {
  console.log("🚀 Deploying Killswitch-Node contracts...\n");
 
  // ─── SIGNERS ────────────────────────────────────────────────────────────────
  const signers = await ethers.getSigners();
  const deployer  = signers[0];
  const guardian  = signers[1];
  const user1     = signers[2];
  const user2     = signers[3];
  const user3     = signers[4];
  // attacker is signers[5] — always use index 5, not 7 (Hardhat only gives 20 signers by default)
  const attacker  = signers[5];
 
  console.log("👤 Deployer (Admin):", deployer.address);
  console.log("🛡️  Guardian:        ", guardian.address);
  console.log("👥 User1:           ", user1.address);
  console.log("💀 Attacker:        ", attacker.address);
  console.log();
 
  // ─── DEPLOY TOKEN ────────────────────────────────────────────────────────────
  const KillswitchToken = await ethers.getContractFactory("KillswitchToken");
  const token = await KillswitchToken.deploy(deployer.address);
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();
  console.log("✅ KillswitchToken deployed:", tokenAddress);
 
  // ─── DEPLOY VAULT (self-contained freeze logic — no circuit breaker arg) ────
  const LiquidityVault = await ethers.getContractFactory("LiquidityVault");
  const vault = await LiquidityVault.deploy(
    tokenAddress,
    deployer.address, // admin  — can emergencyUnfreeze, setMaxWithdrawBps
    guardian.address  // guardian — can freeze/unfreeze
  );
  await vault.waitForDeployment();
  const vaultAddress = await vault.getAddress();
  console.log("✅ LiquidityVault deployed:", vaultAddress);
  console.log(`   Guardian: ${guardian.address}`);
  console.log();
 
  // ─── FUND TEST ACCOUNTS WITH TOKENS ──────────────────────────────────────────
  const FUND_AMOUNT = ethers.parseEther("10000");
 
  const usersToFund = [
    { wallet: user1,    label: "User1" },
    { wallet: user2,    label: "User2" },
    { wallet: user3,    label: "User3" },
    { wallet: attacker, label: "Attacker" },
  ];
 
  for (const { wallet, label } of usersToFund) {
    const tx = await token.transfer(wallet.address, FUND_AMOUNT);
    await tx.wait();
    console.log(`💸 Funded ${label} (${wallet.address.slice(0, 8)}...) with 10000 VLT`);
  }
  console.log();
 
  // ─── SEED VAULT WITH INITIAL LIQUIDITY ───────────────────────────────────────
  const SEED_AMOUNT = ethers.parseEther("5000");
  await (await token.approve(vaultAddress, SEED_AMOUNT)).wait();
  await (await vault.deposit(SEED_AMOUNT)).wait();
  console.log("🏦 Vault seeded with 5000 VLT initial liquidity");
  console.log();
 
  // ─── BUILD CONFIG OBJECT ─────────────────────────────────────────────────────
  const network = await ethers.provider.getNetwork();
 
  const config = {
    network: network.name === "unknown" ? "localhost" : network.name,
    chainId: Number(network.chainId),
    deployedAt: new Date().toISOString(),
    contracts: {
      vault:  vaultAddress,
      token:  tokenAddress,
    },
    guardian: {
      address:       guardian.address,
      privateKey:    "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
    },
    admin: {
      address: deployer.address,
      privateKey: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
    },
    accounts: {
      deployer: deployer.address,
      guardian: guardian.address,
      user1:    user1.address,
      user2:    user2.address,
      user3:    user3.address,
      attacker: attacker.address,
    },
  };
 
  // ─── EXPORT TO ALL MODULES ───────────────────────────────────────────────────
  const scriptDir = __dirname;
  const projectRoot = path.resolve(scriptDir, "../..");
 
  const exportTargets = [
    {
      label: "Frontend (Vite/React)",
      filePath: path.join(projectRoot, "frontend", "config", "contracts.json"),
    },
    {
      label: "Monitoring Engine",
      filePath: path.join(projectRoot, "monitoring-engine", "config", "contracts.json"),
    },
    {
      label: "Attack Simulator",
      filePath: path.join(projectRoot, "attack-simulator", "config", "contracts.json"),
    },
    {
      label: "Contracts (local cache)",
      filePath: path.join(scriptDir, "../deployments.json"),
    },
  ];
 
  for (const target of exportTargets) {
    const dir = path.dirname(target.filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(target.filePath, JSON.stringify(config, null, 2));
    console.log(`📁 Config → ${target.label}`);
    console.log(`   ${target.filePath}`);
  }
 
  // ─── AUTO-UPDATE VITE FRONTEND constants.ts ───────────────────────────────────
  const constantsPath = path.join(projectRoot, "frontend", "src", "lib", "constants.ts");
  const constantsContent = [
    `// ─── Contract Addresses (auto-generated by deploy.ts) ────────────────────────`,
    `// DO NOT EDIT — re-run: npx hardhat run scripts/deploy.ts --network localhost`,
    `// Generated at: ${new Date().toISOString()}`,
    `export const VAULT_ADDRESS  = "${vaultAddress}" as \`0x\${string}\`;`,
    `export const TOKEN_ADDRESS  = "${tokenAddress}" as \`0x\${string}\`;`,
    ``,
    `// ─── Network ─────────────────────────────────────────────────────────────────`,
    `export const CHAIN_ID = ${Number(network.chainId)};`,
    `export const RPC_URL  = "http://localhost:8545";`,
    ``,
    `// ─── Backend ─────────────────────────────────────────────────────────────────`,
    `export const ENGINE_URL = "http://localhost:3001";`,
    ``,
    `// ─── Known roles (from deployments.json) ─────────────────────────────────────`,
    `export const ATTACKER_ADDRESS = "${attacker.address}";`,
  ].join("\n");

  fs.writeFileSync(constantsPath, constantsContent);
  console.log(`\n⚙️  Vite frontend constants.ts auto-updated with live contract addresses`);
 
  // ─── SUMMARY ─────────────────────────────────────────────────────────────────
  console.log("\n" + "─".repeat(56));
  console.log("🎉 DEPLOYMENT COMPLETE");
  console.log("─".repeat(56));
  console.log(`Network:   ${config.network} (chainId: ${config.chainId})`);
  console.log(`Vault:     ${vaultAddress}`);
  console.log(`Token:     ${tokenAddress}`);
  console.log(`Admin:     ${deployer.address}`);
  console.log(`Guardian:  ${guardian.address}`);
  console.log(`Attacker:  ${attacker.address}`);
  console.log("─".repeat(56));
  console.log("Next steps:");
  console.log("  1. cd monitoring-engine && npm run dev");
  console.log("  2. cd frontend && npm run dev");
  console.log("  3. Run attack: cd attack-contracts && npm run attack:microdrain");
  console.log("─".repeat(56));
}
 
main().catch((err) => {
  console.error("❌ Deployment failed:", err);
  process.exit(1);
});
