/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVaultWithEmergency } from "./IVaultWithEmergency";
export type { MasterController } from "./MasterController";
