/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TieredCircuitBreakerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AGGREGATE_TIME_WINDOW"
      | "DEFAULT_ADMIN_ROLE"
      | "GLOBAL_ATTACK_THRESHOLD"
      | "GLOBAL_RISK_SCORE_CAP"
      | "GUARDIAN_ROLE"
      | "RATE_LIMIT_WINDOW"
      | "UPGRADER_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "accountRiskScore"
      | "attackCount"
      | "checkAndRecordWithdrawal"
      | "clearUserRisk"
      | "frozenAssets"
      | "frozenUsers"
      | "getRoleAdmin"
      | "globalEpochWithdrawals"
      | "globalFreezeLevel"
      | "globalRiskScore"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "lastGlobalFreezeTime"
      | "maxTVLWithdrawBps"
      | "maxUserWithdrawPerEpoch"
      | "proxiableUUID"
      | "recordThreat"
      | "renounceRole"
      | "revokeRole"
      | "setAssetFreeze"
      | "setGlobalFreeze"
      | "setUserFreeze"
      | "supportsInterface"
      | "updateRateLimits"
      | "upgradeToAndCall"
      | "userEpochWithdrawals"
      | "windowStartTime"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AggregateThreatDetected"
      | "Initialized"
      | "RateLimitTriggered"
      | "RateLimitsUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TierStatusChanged"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AGGREGATE_TIME_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GLOBAL_ATTACK_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GLOBAL_RISK_SCORE_CAP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GUARDIAN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RATE_LIMIT_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accountRiskScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attackCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkAndRecordWithdrawal",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "clearUserRisk",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "frozenAssets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "frozenUsers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalEpochWithdrawals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "globalFreezeLevel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "globalRiskScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastGlobalFreezeTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTVLWithdrawBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxUserWithdrawPerEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordThreat",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssetFreeze",
    values: [AddressLike, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalFreeze",
    values: [boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserFreeze",
    values: [AddressLike, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRateLimits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userEpochWithdrawals",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "windowStartTime",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "AGGREGATE_TIME_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GLOBAL_ATTACK_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GLOBAL_RISK_SCORE_CAP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GUARDIAN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RATE_LIMIT_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attackCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAndRecordWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearUserRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "frozenAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "frozenUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalEpochWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalFreezeLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastGlobalFreezeTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTVLWithdrawBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxUserWithdrawPerEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordThreat",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAssetFreeze",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalFreeze",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserFreeze",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRateLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userEpochWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "windowStartTime",
    data: BytesLike
  ): Result;
}

export namespace AggregateThreatDetectedEvent {
  export type InputTuple = [attackCount: BigNumberish, totalRisk: BigNumberish];
  export type OutputTuple = [attackCount: bigint, totalRisk: bigint];
  export interface OutputObject {
    attackCount: bigint;
    totalRisk: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateLimitTriggeredEvent {
  export type InputTuple = [
    user: AddressLike,
    attempted: BigNumberish,
    cap: BigNumberish
  ];
  export type OutputTuple = [user: string, attempted: bigint, cap: bigint];
  export interface OutputObject {
    user: string;
    attempted: bigint;
    cap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateLimitsUpdatedEvent {
  export type InputTuple = [newTvlBps: BigNumberish, newUserCap: BigNumberish];
  export type OutputTuple = [newTvlBps: bigint, newUserCap: bigint];
  export interface OutputObject {
    newTvlBps: bigint;
    newUserCap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierStatusChangedEvent {
  export type InputTuple = [
    level: BigNumberish,
    target: AddressLike,
    reason: string
  ];
  export type OutputTuple = [level: bigint, target: string, reason: string];
  export interface OutputObject {
    level: bigint;
    target: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TieredCircuitBreaker extends BaseContract {
  connect(runner?: ContractRunner | null): TieredCircuitBreaker;
  waitForDeployment(): Promise<this>;

  interface: TieredCircuitBreakerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AGGREGATE_TIME_WINDOW: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GLOBAL_ATTACK_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  GLOBAL_RISK_SCORE_CAP: TypedContractMethod<[], [bigint], "view">;

  GUARDIAN_ROLE: TypedContractMethod<[], [string], "view">;

  RATE_LIMIT_WINDOW: TypedContractMethod<[], [bigint], "view">;

  UPGRADER_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  accountRiskScore: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  attackCount: TypedContractMethod<[], [bigint], "view">;

  checkAndRecordWithdrawal: TypedContractMethod<
    [
      user: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      currentTVL: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  clearUserRisk: TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  frozenAssets: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  frozenUsers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  globalEpochWithdrawals: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  globalFreezeLevel: TypedContractMethod<[], [bigint], "view">;

  globalRiskScore: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      admin: AddressLike,
      _maxTVLWithdrawBps: BigNumberish,
      _maxUserWithdrawPerEpoch: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  lastGlobalFreezeTime: TypedContractMethod<[], [bigint], "view">;

  maxTVLWithdrawBps: TypedContractMethod<[], [bigint], "view">;

  maxUserWithdrawPerEpoch: TypedContractMethod<[], [bigint], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  recordThreat: TypedContractMethod<
    [user: AddressLike, riskAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAssetFreeze: TypedContractMethod<
    [asset: AddressLike, frozen: boolean, reason: string],
    [void],
    "nonpayable"
  >;

  setGlobalFreeze: TypedContractMethod<
    [frozen: boolean, reason: string],
    [void],
    "nonpayable"
  >;

  setUserFreeze: TypedContractMethod<
    [user: AddressLike, frozen: boolean, reason: string],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateRateLimits: TypedContractMethod<
    [tvlBps: BigNumberish, userCap: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  userEpochWithdrawals: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  windowStartTime: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AGGREGATE_TIME_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GLOBAL_ATTACK_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GLOBAL_RISK_SCORE_CAP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GUARDIAN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RATE_LIMIT_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accountRiskScore"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "attackCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkAndRecordWithdrawal"
  ): TypedContractMethod<
    [
      user: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      currentTVL: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "clearUserRisk"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "frozenAssets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "frozenUsers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "globalEpochWithdrawals"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "globalFreezeLevel"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "globalRiskScore"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      admin: AddressLike,
      _maxTVLWithdrawBps: BigNumberish,
      _maxUserWithdrawPerEpoch: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lastGlobalFreezeTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxTVLWithdrawBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxUserWithdrawPerEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordThreat"
  ): TypedContractMethod<
    [user: AddressLike, riskAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAssetFreeze"
  ): TypedContractMethod<
    [asset: AddressLike, frozen: boolean, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGlobalFreeze"
  ): TypedContractMethod<
    [frozen: boolean, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUserFreeze"
  ): TypedContractMethod<
    [user: AddressLike, frozen: boolean, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateRateLimits"
  ): TypedContractMethod<
    [tvlBps: BigNumberish, userCap: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "userEpochWithdrawals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "windowStartTime"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AggregateThreatDetected"
  ): TypedContractEvent<
    AggregateThreatDetectedEvent.InputTuple,
    AggregateThreatDetectedEvent.OutputTuple,
    AggregateThreatDetectedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "RateLimitTriggered"
  ): TypedContractEvent<
    RateLimitTriggeredEvent.InputTuple,
    RateLimitTriggeredEvent.OutputTuple,
    RateLimitTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "RateLimitsUpdated"
  ): TypedContractEvent<
    RateLimitsUpdatedEvent.InputTuple,
    RateLimitsUpdatedEvent.OutputTuple,
    RateLimitsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TierStatusChanged"
  ): TypedContractEvent<
    TierStatusChangedEvent.InputTuple,
    TierStatusChangedEvent.OutputTuple,
    TierStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AggregateThreatDetected(uint256,uint256)": TypedContractEvent<
      AggregateThreatDetectedEvent.InputTuple,
      AggregateThreatDetectedEvent.OutputTuple,
      AggregateThreatDetectedEvent.OutputObject
    >;
    AggregateThreatDetected: TypedContractEvent<
      AggregateThreatDetectedEvent.InputTuple,
      AggregateThreatDetectedEvent.OutputTuple,
      AggregateThreatDetectedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "RateLimitTriggered(address,uint256,uint256)": TypedContractEvent<
      RateLimitTriggeredEvent.InputTuple,
      RateLimitTriggeredEvent.OutputTuple,
      RateLimitTriggeredEvent.OutputObject
    >;
    RateLimitTriggered: TypedContractEvent<
      RateLimitTriggeredEvent.InputTuple,
      RateLimitTriggeredEvent.OutputTuple,
      RateLimitTriggeredEvent.OutputObject
    >;

    "RateLimitsUpdated(uint256,uint256)": TypedContractEvent<
      RateLimitsUpdatedEvent.InputTuple,
      RateLimitsUpdatedEvent.OutputTuple,
      RateLimitsUpdatedEvent.OutputObject
    >;
    RateLimitsUpdated: TypedContractEvent<
      RateLimitsUpdatedEvent.InputTuple,
      RateLimitsUpdatedEvent.OutputTuple,
      RateLimitsUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TierStatusChanged(uint8,address,string)": TypedContractEvent<
      TierStatusChangedEvent.InputTuple,
      TierStatusChangedEvent.OutputTuple,
      TierStatusChangedEvent.OutputObject
    >;
    TierStatusChanged: TypedContractEvent<
      TierStatusChangedEvent.InputTuple,
      TierStatusChangedEvent.OutputTuple,
      TierStatusChangedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
