/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ITieredCircuitBreakerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkAndRecordWithdrawal"
      | "globalFreezeLevel"
      | "lastGlobalFreezeTime"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkAndRecordWithdrawal",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "globalFreezeLevel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastGlobalFreezeTime",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "checkAndRecordWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalFreezeLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastGlobalFreezeTime",
    data: BytesLike
  ): Result;
}

export interface ITieredCircuitBreaker extends BaseContract {
  connect(runner?: ContractRunner | null): ITieredCircuitBreaker;
  waitForDeployment(): Promise<this>;

  interface: ITieredCircuitBreakerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkAndRecordWithdrawal: TypedContractMethod<
    [
      user: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      currentTVL: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  globalFreezeLevel: TypedContractMethod<[], [bigint], "view">;

  lastGlobalFreezeTime: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkAndRecordWithdrawal"
  ): TypedContractMethod<
    [
      user: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      currentTVL: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "globalFreezeLevel"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastGlobalFreezeTime"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
