/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITieredCircuitBreaker,
  ITieredCircuitBreakerInterface,
} from "../../../contracts/LiquidityVault.sol/ITieredCircuitBreaker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "currentTVL",
        type: "uint256",
      },
    ],
    name: "checkAndRecordWithdrawal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "globalFreezeLevel",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastGlobalFreezeTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITieredCircuitBreaker__factory {
  static readonly abi = _abi;
  static createInterface(): ITieredCircuitBreakerInterface {
    return new Interface(_abi) as ITieredCircuitBreakerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITieredCircuitBreaker {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ITieredCircuitBreaker;
  }
}
