/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVaultWithEmergency,
  IVaultWithEmergencyInterface,
} from "../../../../contracts/security/MasterController.sol/IVaultWithEmergency";

const _abi = [
  {
    inputs: [],
    name: "emergencyUnfreeze",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "emergencyWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "freeze",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVaultWithEmergency__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultWithEmergencyInterface {
    return new Interface(_abi) as IVaultWithEmergencyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVaultWithEmergency {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IVaultWithEmergency;
  }
}
