// ─── Contract Addresses (auto-generated by deploy.ts) ────────────────────────
// DO NOT EDIT — re-run: npx hardhat run scripts/deploy.ts --network localhost
// Generated at: 2026-04-18T13:17:10.135Z
export const VAULT_ADDRESS  = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as `0x${string}`;
export const TOKEN_ADDRESS  = "0x5FbDB2315678afecb367f032d93F642f64180aa3" as `0x${string}`;

// ─── Network ─────────────────────────────────────────────────────────────────
export const CHAIN_ID = 31337;
export const RPC_URL  = "http://localhost:8545";

// ─── Backend ─────────────────────────────────────────────────────────────────
export const ENGINE_URL = "http://localhost:3001";

// ─── Known roles (from deployments.json) ─────────────────────────────────────
export const ATTACKER_ADDRESS = "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc";