// ─── Contract Addresses (auto-generated by deploy.ts) ────────────────────────
// DO NOT EDIT — re-run: npx hardhat run scripts/deploy.ts --network localhost
// Generated at: 2026-04-18T08:27:40.780Z
export const VAULT_ADDRESS  = "0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690" as `0x${string}`;
export const TOKEN_ADDRESS  = "0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E" as `0x${string}`;

// ─── Network ─────────────────────────────────────────────────────────────────
export const CHAIN_ID = 31337;
export const RPC_URL  = "http://localhost:8545";

// ─── Backend ─────────────────────────────────────────────────────────────────
export const ENGINE_URL = "http://localhost:3001";

// ─── Known roles (from deployments.json) ─────────────────────────────────────
export const ATTACKER_ADDRESS = "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc";