/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ReentrancyAttackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attack"
      | "attackRounds"
      | "attackRunning"
      | "exfiltrate"
      | "getStatus"
      | "owner"
      | "token"
      | "totalExtracted"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttackBlocked"
      | "AttackComplete"
      | "AttackStarted"
      | "RoundExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attack",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attackRounds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attackRunning",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "exfiltrate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getStatus", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalExtracted",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(functionFragment: "attack", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attackRounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attackRunning",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exfiltrate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalExtracted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace AttackBlockedEvent {
  export type InputTuple = [round: BigNumberish, reason: string];
  export type OutputTuple = [round: bigint, reason: string];
  export interface OutputObject {
    round: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttackCompleteEvent {
  export type InputTuple = [totalExtracted: BigNumberish, vaultFrozen: boolean];
  export type OutputTuple = [totalExtracted: bigint, vaultFrozen: boolean];
  export interface OutputObject {
    totalExtracted: bigint;
    vaultFrozen: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttackStartedEvent {
  export type InputTuple = [depositAmount: BigNumberish, rounds: BigNumberish];
  export type OutputTuple = [depositAmount: bigint, rounds: bigint];
  export interface OutputObject {
    depositAmount: bigint;
    rounds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundExecutedEvent {
  export type InputTuple = [
    round: BigNumberish,
    amount: BigNumberish,
    vaultRemainder: BigNumberish
  ];
  export type OutputTuple = [
    round: bigint,
    amount: bigint,
    vaultRemainder: bigint
  ];
  export interface OutputObject {
    round: bigint;
    amount: bigint;
    vaultRemainder: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReentrancyAttacker extends BaseContract {
  connect(runner?: ContractRunner | null): ReentrancyAttacker;
  waitForDeployment(): Promise<this>;

  interface: ReentrancyAttackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attack: TypedContractMethod<
    [
      depositAmount: BigNumberish,
      withdrawAmount: BigNumberish,
      rounds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  attackRounds: TypedContractMethod<[], [bigint], "view">;

  attackRunning: TypedContractMethod<[], [boolean], "view">;

  exfiltrate: TypedContractMethod<[], [void], "nonpayable">;

  getStatus: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean] & {
        contractVLT: bigint;
        vaultVLT: bigint;
        myVaultDeposit: bigint;
        vaultFrozen: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  token: TypedContractMethod<[], [string], "view">;

  totalExtracted: TypedContractMethod<[], [bigint], "view">;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attack"
  ): TypedContractMethod<
    [
      depositAmount: BigNumberish,
      withdrawAmount: BigNumberish,
      rounds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attackRounds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "attackRunning"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "exfiltrate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean] & {
        contractVLT: bigint;
        vaultVLT: bigint;
        myVaultDeposit: bigint;
        vaultFrozen: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalExtracted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AttackBlocked"
  ): TypedContractEvent<
    AttackBlockedEvent.InputTuple,
    AttackBlockedEvent.OutputTuple,
    AttackBlockedEvent.OutputObject
  >;
  getEvent(
    key: "AttackComplete"
  ): TypedContractEvent<
    AttackCompleteEvent.InputTuple,
    AttackCompleteEvent.OutputTuple,
    AttackCompleteEvent.OutputObject
  >;
  getEvent(
    key: "AttackStarted"
  ): TypedContractEvent<
    AttackStartedEvent.InputTuple,
    AttackStartedEvent.OutputTuple,
    AttackStartedEvent.OutputObject
  >;
  getEvent(
    key: "RoundExecuted"
  ): TypedContractEvent<
    RoundExecutedEvent.InputTuple,
    RoundExecutedEvent.OutputTuple,
    RoundExecutedEvent.OutputObject
  >;

  filters: {
    "AttackBlocked(uint256,string)": TypedContractEvent<
      AttackBlockedEvent.InputTuple,
      AttackBlockedEvent.OutputTuple,
      AttackBlockedEvent.OutputObject
    >;
    AttackBlocked: TypedContractEvent<
      AttackBlockedEvent.InputTuple,
      AttackBlockedEvent.OutputTuple,
      AttackBlockedEvent.OutputObject
    >;

    "AttackComplete(uint256,bool)": TypedContractEvent<
      AttackCompleteEvent.InputTuple,
      AttackCompleteEvent.OutputTuple,
      AttackCompleteEvent.OutputObject
    >;
    AttackComplete: TypedContractEvent<
      AttackCompleteEvent.InputTuple,
      AttackCompleteEvent.OutputTuple,
      AttackCompleteEvent.OutputObject
    >;

    "AttackStarted(uint256,uint256)": TypedContractEvent<
      AttackStartedEvent.InputTuple,
      AttackStartedEvent.OutputTuple,
      AttackStartedEvent.OutputObject
    >;
    AttackStarted: TypedContractEvent<
      AttackStartedEvent.InputTuple,
      AttackStartedEvent.OutputTuple,
      AttackStartedEvent.OutputObject
    >;

    "RoundExecuted(uint256,uint256,uint256)": TypedContractEvent<
      RoundExecutedEvent.InputTuple,
      RoundExecutedEvent.OutputTuple,
      RoundExecutedEvent.OutputObject
    >;
    RoundExecuted: TypedContractEvent<
      RoundExecutedEvent.InputTuple,
      RoundExecutedEvent.OutputTuple,
      RoundExecutedEvent.OutputObject
    >;
  };
}
